[server]
port = 8501
headless = true
enableCORS = false
enableXsrfProtection = false

[theme]
primaryColor = "#FF6B6B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

[browser]
gatherUsageStats = false

[global]
# Application metadata
showWarningOnDirectExecution = false

# Custom app metadata (accessible via st.get_option)
[runner]
magicEnabled = true
installTracer = false
fixMatplotlib = true 